version: "3.9"
services:
  bot:
    build: .
    restart: always
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: ${MONGO_DATABASE}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CHATEX_REFRESH_TOKEN: ${CHATEX_REFRESH_TOKEN}
    networks:
      - makesure-net
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    networks:
      - makesure-net
networks:
  makesure-net:
    name: makesure-net
